### ISSUE TITLE
Cannot read property 'throttle' of null

### ISSUE THREAD

**Issue by schnti** [alexbain/lirc_node#11]
I'm using this plugin [node-red-contrib-lirc](https://github.com/andrewmk/node-red-contrib-lirc) with dependency to this lirc_node lib and getting the following error:

Can anyone help me?

`Uncaught Exception:
1 Oct 12:38:39 - TypeError: Cannot read property 'throttle' of null
at /home/pi/.node-red/node_modules/node-red-contrib-lirc/node_modules/lirc_node/lib/irreceive.js:143:22
at Array.forEach (native)
at IRReceive._handleIRData (/home/pi/.node-red/node_modules/node-red-contrib-lirc/node_modules/lirc_node/lib/irreceive.js:140:20)
at emitOne (events.js:77:13)
at Socket.emit (events.js:169:7)
at readableAddChunk (_stream_readable.js:146:16)
at Socket.Readable.push (_stream_readable.js:110:10)
at Pipe.onread (net.js:523:20)`

**Comment by ddavy** [comment]
Hi,

Replace line 129 in irreceive.js:
`this.callbacks[listenerId] = null;` to `delete this.callbacks[listenerId];`

When removing a listener, the callback gets replaced by `null`. But when looping through the callbacks, it tries to read the property `throttle` of null. As far as I know, this is a bug and should be fixed.

Hope this helps!
